project:
  type: website

website:
  title: "CXH's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd # add your posts.qmd file to your navbar!
      - talks.qmd # add your talk.qmd file to your navbar !
      - href: about.qmd
        text: About
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



